apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: NST-Ai
  name: NST-Ai-pvc
  namespace: NST-Ai
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi